### ISSUE TITLE
取消 时区注释后运行报错

### ISSUE THREAD

**Issue by wyap-echo** [8838/Telegram-Name-Updating#1]
环境 python3.7 
取消注释的是这两行
 Set time zone to UTC+8
 ln -sf /usr/share/zoneinfo/Asia/Chongqing /etc/localtime

File "tg_username_update.py", line 40
    Set time zone to UTC+8
           ^
SyntaxError: invalid syntax

**Comment by 8838** [comment]
小程序是根据vps里的时间变更时间的，运行前把vps时间调整为你想要的时区即可

**Comment by wyap-echo** [comment]
谢谢 老哥 改好了
